<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Transliterator;

class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (Category::count()) {
            Category::truncate();
        }

        $grades = [
            ['name' => 'کلاس اول', 'slug' => 'first-elementary', 'type' => 'grade'],
            ['name' => 'کلاس دوم', 'slug' => 'second-elementary', 'type' => 'grade'],
            ['name' => 'کلاس سوم', 'slug' => 'third-elementary', 'type' => 'grade'],
            ['name' => 'کلاس چهارم', 'slug' => 'fourth-elementary', 'type' => 'grade'],
            ['name' => 'کلاس پنجم', 'slug' => 'fifth-elementary', 'type' => 'grade'],
            ['name' => 'کلاس ششم', 'slug' => 'sixth-elementary', 'type' => 'grade'],
        ];

        $subjects = [
            'first-elementary' => [
                // ['name' => 'آموزش قرآن', 'slug' => 'quran', 'type' => 'subject', 'icon' => 'HiOutlineBookOpen'],
                ['name' => 'فارسی', 'slug' => 'farsi', 'type' => 'subject', 'icon' => 'HiOutlinePencilSquare'],
                ['name' => 'ریاضی', 'slug' => 'math', 'type' => 'subject', 'icon' => 'HiOutlineCalculator'],
                ['name' => 'علوم تجربی', 'slug' => 'science', 'type' => 'subject', 'icon' => 'HiOutlineBeaker'],
            ],
            'second-elementary' => [
                // ['name' => 'آموزش قرآن', 'slug' => 'quran', 'type' => 'subject', 'icon' => 'HiOutlineBookOpen'],
                ['name' => 'هدیه‌های آسمان', 'slug' => 'hedyeh-aseman', 'type' => 'subject', 'icon' => 'HiOutlineHandRaised'],
                ['name' => 'فارسی', 'slug' => 'farsi', 'type' => 'subject', 'icon' => 'HiOutlinePencilSquare'],
                ['name' => 'ریاضی', 'slug' => 'math', 'type' => 'subject', 'icon' => 'HiOutlineCalculator'],
                ['name' => 'علوم تجربی', 'slug' => 'science', 'type' => 'subject', 'icon' => 'HiOutlineBeaker'],
            ],
            'third-elementary' => [
                // ['name' => 'آموزش قرآن', 'slug' => 'quran', 'type' => 'subject', 'icon' => 'HiOutlineBookOpen'],
                ['name' => 'هدیه‌های آسمان', 'slug' => 'hedyeh-aseman', 'type' => 'subject', 'icon' => 'HiOutlineHandRaised'],
                ['name' => 'فارسی', 'slug' => 'farsi', 'type' => 'subject', 'icon' => 'HiOutlinePencilSquare'],
                ['name' => 'ریاضی', 'slug' => 'math', 'type' => 'subject', 'icon' => 'HiOutlineCalculator'],
                ['name' => 'علوم تجربی', 'slug' => 'science', 'type' => 'subject', 'icon' => 'HiOutlineBeaker'],
                ['name' => 'مطالعات اجتماعی', 'slug' => 'social-studies', 'type' => 'subject', 'icon' => 'HiOutlineUserGroup'],
            ],
            'fourth-elementary' => [
                // ['name' => 'آموزش قرآن', 'slug' => 'quran', 'type' => 'subject', 'icon' => 'HiOutlineBookOpen'],
                ['name' => 'هدیه‌های آسمان', 'slug' => 'hedyeh-aseman', 'type' => 'subject', 'icon' => 'HiOutlineHandRaised'],
                ['name' => 'فارسی', 'slug' => 'farsi', 'type' => 'subject', 'icon' => 'HiOutlinePencilSquare'],
                ['name' => 'ریاضی', 'slug' => 'math', 'type' => 'subject', 'icon' => 'HiOutlineCalculator'],
                ['name' => 'علوم تجربی', 'slug' => 'science', 'type' => 'subject', 'icon' => 'HiOutlineBeaker'],
                ['name' => 'مطالعات اجتماعی', 'slug' => 'social-studies', 'type' => 'subject', 'icon' => 'HiOutlineUserGroup'],
            ],
            'fifth-elementary' => [
                // ['name' => 'آموزش قرآن', 'slug' => 'quran', 'type' => 'subject', 'icon' => 'HiOutlineBookOpen'],
                ['name' => 'هدیه‌های آسمان', 'slug' => 'hedyeh-aseman', 'type' => 'subject', 'icon' => 'HiOutlineHandRaised'],
                ['name' => 'فارسی', 'slug' => 'farsi', 'type' => 'subject', 'icon' => 'HiOutlinePencilSquare'],
                ['name' => 'ریاضی', 'slug' => 'math', 'type' => 'subject', 'icon' => 'HiOutlineCalculator'],
                ['name' => 'علوم تجربی', 'slug' => 'science', 'type' => 'subject', 'icon' => 'HiOutlineBeaker'],
                ['name' => 'مطالعات اجتماعی', 'slug' => 'social-studies', 'type' => 'subject', 'icon' => 'HiOutlineUserGroup'],
            ],
            'sixth-elementary' => [
                // ['name' => 'آموزش قرآن', 'slug' => 'quran', 'type' => 'subject', 'icon' => 'HiOutlineBookOpen'],
                ['name' => 'هدیه‌های آسمان', 'slug' => 'hedyeh-aseman', 'type' => 'subject', 'icon' => 'HiOutlineHandRaised'],
                ['name' => 'فارسی', 'slug' => 'farsi', 'type' => 'subject', 'icon' => 'HiOutlinePencilSquare'],
                ['name' => 'ریاضی', 'slug' => 'math', 'type' => 'subject', 'icon' => 'HiOutlineCalculator'],
                ['name' => 'علوم تجربی', 'slug' => 'science', 'type' => 'subject', 'icon' => 'HiOutlineBeaker'],
                ['name' => 'مطالعات اجتماعی', 'slug' => 'social-studies', 'type' => 'subject', 'icon' => 'HiOutlineUserGroup'],
                ['name' => 'تفکر و پژوهش', 'slug' => 'thinking-research', 'type' => 'subject', 'icon' => 'HiOutlineLightBulb'],
                ['name' => 'کار و فناوری', 'slug' => 'work-technology', 'type' => 'subject', 'icon' => 'HiOutlineWrenchScrewdriver'],
            ],
        ];

        $topics = [
            'first-elementary' => [
                // 'quran' => [
                //     ['name' => 'درس اول: به نام خدا، بسم الله', 'slug' => 'lesson1', 'type' => 'topic'],
                //     ['name' => 'درس دوم: نعمت های خدا', 'slug' => 'lesson2', 'type' => 'topic'],
                //     ['name' => 'درس سوم: خانه ی ما', 'slug' => 'lesson3', 'type' => 'topic'],
                //     ['name' => 'درس چهارم: قرآن بخوانیم', 'slug' => 'lesson4', 'type' => 'topic'],
                //     ['name' => 'درس پنجم: کودک مسلمان', 'slug' => 'lesson5', 'type' => 'topic'],
                //     ['name' => 'درس ششم: مدرسه ی ما', 'slug' => 'lesson6', 'type' => 'topic'],
                //     ['name' => 'درس هفتم: پیامبران خدا ', 'slug' => 'lesson7', 'type' => 'topic'],
                // ],

                'farsi' => [
                    ['name' => 'نگاره‌ی 1: به خانه‌ی ما خوش آمدی', 'slug' => 'image1', 'type' => 'topic'],
                    ['name' => 'نگاره‌ 2: بچه ها، آماده!', 'slug' => 'image2', 'type' => 'topic'],
                    ['name' => 'نگاره‌ی 3: یک٬ دو و سه راه مدرسه', 'slug' => 'image3', 'type' => 'topic'],
                    ['name' => 'نگاره‌ی 4: به مدرسه رسیدیم', 'slug' => 'image4', 'type' => 'topic'],
                    ['name' => 'نگاره‌ی 5: از کلاس ما چه خبر؟', 'slug' => 'image5', 'type' => 'topic'],
                    ['name' => 'نگاره‌ی 6: بازی، بازی، تماشا', 'slug' => 'image6', 'type' => 'topic'],
                    ['name' => 'نگاره‌ی 7: به به چه روستایی', 'slug' => 'image7', 'type' => 'topic'],
                    ['name' => 'نگاره‌ی 8: چه دنیای قشنگی', 'slug' => 'image8', 'type' => 'topic'],
                    ['name' => 'نگاره‌ی 9: در مسجد محله', 'slug' => 'image9', 'type' => 'topic'],
                    ['name' => 'نگاره‌ی 10: نوروز در خانه‌ی ما', 'slug' => 'image10', 'type' => 'topic'],
                    ['name' => 'درس 1: آ ا ــ بـ ب', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس 2: اَ ـَ ــ د', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس 3: مـ م ــ سـ س', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس 4: او و ــ تـ ت', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس 5: ر ــ نـ ن', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس 6: ایـ یـ ی ای ــ ز', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس 7: اِ ـِ ــ ـه ه ــ شـ ش', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس 8: یـ ى ــ اُ ـُ', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس 9: کـ ک ــ و', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس 10: پـ پ ــ گـ گ', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس 11: فـ ف ــ خـ خ', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس 12: قـ ق ــ لـ ل', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس 13: جـ ج ــ ـُ استثنا', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'درس 14: هـ ـهـ ـه ه ــ چـ چ', 'slug' => 'lesson14', 'type' => 'topic'],
                    ['name' => 'درس 15: ژ ــ خوا', 'slug' => 'lesson15', 'type' => 'topic'],
                    ['name' => 'درس 16: در بازار ” تشدید ـّ “', 'slug' => 'lesson16', 'type' => 'topic'],
                    ['name' => 'درس 17: صدایِ موج ”صـ ص“ ــ سفرِ دلپذیر ”ذ“', 'slug' => 'lesson17', 'type' => 'topic'],
                    ['name' => 'درس 18: علی و معصومه ”عـ ـعـ ـع ع“ ــ مثلِ خورشید ”ثـ ث“', 'slug' => 'lesson18', 'type' => 'topic'],
                    ['name' => 'درس 19: حَلَزون ”حـ ح“', 'slug' => 'lesson19', 'type' => 'topic'],
                    ['name' => 'درس 20: رضا ”ضـ ض“ ــ خاطرات انقلاب ”ط“', 'slug' => 'lesson20', 'type' => 'topic'],
                    ['name' => 'درس 21: لاک‌پشت و مرغابی‌ها ”غـ ـغـ ـغ غ“', 'slug' => 'lesson21', 'type' => 'topic'],
                    ['name' => 'درس 22: پیامبر مهربان “ظ”', 'slug' => 'lesson22', 'type' => 'topic'],

                ],
                'math' => [
                    ['name' => 'تم1', 'slug' => 'theme1', 'type' => 'topic'],
                    ['name' => 'تم2', 'slug' => 'theme2', 'type' => 'topic'],
                    ['name' => 'تم3', 'slug' => 'theme3', 'type' => 'topic'],
                    ['name' => 'تم4', 'slug' => 'theme4', 'type' => 'topic'],
                    ['name' => 'تم5', 'slug' => 'theme5', 'type' => 'topic'],
                    ['name' => 'تم6', 'slug' => 'theme6', 'type' => 'topic'],
                    ['name' => 'تم7', 'slug' => 'theme7', 'type' => 'topic'],
                    ['name' => 'تم8', 'slug' => 'theme8', 'type' => 'topic'],
                    ['name' => 'تم9', 'slug' => 'theme9', 'type' => 'topic'],
                    ['name' => 'تم10', 'slug' => 'theme10', 'type' => 'topic'],
                    ['name' => 'تم11', 'slug' => 'theme11', 'type' => 'topic'],
                    ['name' => 'تم12', 'slug' => 'theme12', 'type' => 'topic'],
                    ['name' => 'تم13', 'slug' => 'theme13', 'type' => 'topic'],
                    ['name' => 'تم14', 'slug' => 'theme14', 'type' => 'topic'],
                    ['name' => 'تم15', 'slug' => 'theme15', 'type' => 'topic'],
                    ['name' => 'تم16', 'slug' => 'theme16', 'type' => 'topic'],
                    ['name' => 'تم17', 'slug' => 'theme17', 'type' => 'topic'],
                    ['name' => 'تم18', 'slug' => 'theme18', 'type' => 'topic'],
                    ['name' => 'تم19', 'slug' => 'theme19', 'type' => 'topic'],
                    ['name' => 'تم20', 'slug' => 'theme20', 'type' => 'topic'],
                    ['name' => 'تم21', 'slug' => 'theme21', 'type' => 'topic'],
                    ['name' => 'تم22', 'slug' => 'theme22', 'type' => 'topic'],
                    ['name' => 'تم23', 'slug' => 'theme23', 'type' => 'topic'],
                    ['name' => 'تم24', 'slug' => 'theme24', 'type' => 'topic'],
                    ['name' => 'تم25', 'slug' => 'theme25', 'type' => 'topic'],
                ],
                'science' => [
                    ['name' => 'فصل 1: زنگ علوم', 'slug' => 'season1', 'type' => 'topic'],
                    ['name' => 'فصل 2: سلام، به من نگاه کن!', 'slug' => 'season2', 'type' => 'topic'],
                    ['name' => 'فصل 3: سالم باش، شاداب باش', 'slug' => 'season3', 'type' => 'topic'],
                    ['name' => 'فصل 4: دنیای جانوران', 'slug' => 'season4', 'type' => 'topic'],
                    ['name' => 'فصل 5: دنیای گیاهان', 'slug' => 'season5', 'type' => 'topic'],
                    ['name' => 'فصل 6: زمین خانه ی پر آب ما', 'slug' => 'season6', 'type' => 'topic'],
                    ['name' => 'فصل 7: زمین خانه ی سنگی ما', 'slug' => 'season7', 'type' => 'topic'],
                    ['name' => 'فصل 8: چه می خواهم بسازم؟', 'slug' => 'season8', 'type' => 'topic'],
                    ['name' => 'فصل 9: زمین خانه ی خاکی ما', 'slug' => 'season9', 'type' => 'topic'],
                    ['name' => 'فصل 10: در اطراف ما هوا وجود دارد', 'slug' => 'season10', 'type' => 'topic'],
                    ['name' => 'فصل 11: دنیای سرد و گرم', 'slug' => 'season11', 'type' => 'topic'],
                    ['name' => 'فصل 12: از خانه تا مدرسه', 'slug' => 'season12', 'type' => 'topic'],
                    ['name' => 'فصل 13: آهن ربای من', 'slug' => 'season13', 'type' => 'topic'],
                    ['name' => 'فصل 14: از گذشته تا آینده', 'slug' => 'season14', 'type' => 'topic'],
                ],
            ],
            'second-elementary' => [
                // 'quran' => [
                //     ['name' => 'درس اول: الف کوچک/سکون', 'slug' => 'lesson1', 'type' => 'topic'],
                //     ['name' => 'درس دوم: تشدید/اتصالات', 'slug' => 'lesson2', 'type' => 'topic'],
                //     ['name' => 'درس سوم: سوره ی حمد/ک', 'slug' => 'lesson3', 'type' => 'topic'],
                //     ['name' => 'درس چهارم: سوره ی ناس/ة', 'slug' => 'lesson4', 'type' => 'topic'],
                //     ['name' => 'درس پنجم: سوره ی فلق/تنوین ها', 'slug' => 'lesson5', 'type' => 'topic'],
                //     ['name' => 'درس ششم: سوره ی توحید/ه و ، ه ی', 'slug' => 'lesson6', 'type' => 'topic'],
                //     ['name' => 'درس هفتم: سوره نصر/فتح مکه/ء (همزه)', 'slug' => 'lesson7', 'type' => 'topic'],
                //     ['name' => 'درس هشتم: سوره کوثر/ئ/کودک خدا پرست', 'slug' => 'lesson8', 'type' => 'topic'],
                //     ['name' => 'درس نهم: سوره ی عصر', 'slug' => 'lesson9', 'type' => 'topic'],
                //     ['name' => 'درس دهم: سوره ی فیل/اصحاب فیل/سوره ی ماعون', 'slug' => 'lesson10', 'type' => 'topic'],
                //     ['name' => 'درس یازدهم: سوره ی کافرون', 'slug' => 'lesson11', 'type' => 'topic'],
                //     ['name' => 'درس دوازدهم: سوره انشراح', 'slug' => 'lesson12', 'type' => 'topic'],
                //     ['name' => 'درس سیزدهم: سوره تین/قهرمان بت شکن', 'slug' => 'lesson13', 'type' => 'topic'],
                //     ['name' => 'درس چهاردهم: سوره ی قدر/باغی میان آتش', 'slug' => 'lesson14', 'type' => 'topic'],
                // ],
                'hedyeh-aseman' => [
                    ['name' => 'درس اول: هدیه های خدا', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: پرندگان چه می گویند؟', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: خاطره ی ماه', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: مهربان‌تر از مادر', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس پنجم: می خواهم وضو بگیرم', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: پیامبران خدا', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: مهمان کوچک', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس هشتم: جشن میلاد', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: اهل بیت پیامبر', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: خانواده ی مهربان', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس یازدهم: نماز بخوانیم', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: پدر مهربان', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سیزدهم: بهترین دوست', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'درس چهاردهم: دعای باران', 'slug' => 'lesson14', 'type' => 'topic'],
                    ['name' => 'درس پانزدهم: بچه ها سلام!', 'slug' => 'lesson15', 'type' => 'topic'],
                    ['name' => 'درس شانزدهم: طبیعت زیبا', 'slug' => 'lesson16', 'type' => 'topic'],
                    ['name' => 'درس هفدهم: وقت نماز', 'slug' => 'lesson17', 'type' => 'topic'],
                    ['name' => 'درس هجدهم: راه خوش بختی', 'slug' => 'lesson18', 'type' => 'topic'],
                    ['name' => 'درس نوزدهم: جشن بزرگ', 'slug' => 'lesson19', 'type' => 'topic'],
                    ['name' => 'درس بیستم: در کنار سفره', 'slug' => 'lesson20', 'type' => 'topic'],
                ],
                'farsi' => [
                    ['name' => 'درس اول: کتابخانه‌ی کلاس ما', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: مسجد محلّه‌ی ما', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: خرس کوچولو', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: مدرسه‌ی خرگوش‌ها', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس پنجم: چوپان درستکار', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: کوشا و نوشا', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: دوستان ما', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس هشتم: از همه مهربان‌تر', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: زیارت', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: هنرمند', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس یازدهم: درس آزاد', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: فردوسی', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سیزدهم: ایرانِ زیبا', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'درس چهاردهم: پرچم', 'slug' => 'lesson14', 'type' => 'topic'],
                    ['name' => 'درس پانزدهم: نوروز', 'slug' => 'lesson15', 'type' => 'topic'],
                    ['name' => 'درس شانزدهم: پرواز قطره', 'slug' => 'lesson16', 'type' => 'topic'],
                    ['name' => 'درس هفدهم: مثل دانشمندان', 'slug' => 'lesson17', 'type' => 'topic'],

                ],
                'math' => [
                    ['name' => 'فصل اول: عدد و رقم', 'slug' => 'season1', 'type' => 'topic'],
                    ['name' => 'فصل دوم: جمع و تفریق اعداد دو رقمی', 'slug' => 'season2', 'type' => 'topic'],
                    ['name' => 'فصل سوم: اشکال هندسی', 'slug' => 'season3', 'type' => 'topic'],
                    ['name' => 'فصل چهارم: عددهای سه رقمی', 'slug' => 'season4', 'type' => 'topic'],
                    ['name' => 'فصل پنجم: اندازه گیری', 'slug' => 'season5', 'type' => 'topic'],
                    ['name' => 'فصل ششم: جمع و تفریق اعداد سه رقمی', 'slug' => 'season6', 'type' => 'topic'],
                    ['name' => 'فصل هفتم: کسر و احتمال', 'slug' => 'season7', 'type' => 'topic'],
                    ['name' => 'فصل هشتم: آمار و نمودار', 'slug' => 'season8', 'type' => 'topic'],
                ],
                'science' => [
                    ['name' => 'فصل اول: زنگ علوم (گردشی در باغ)', 'slug' => 'season1', 'type' => 'topic'],
                    ['name' => 'فصل دوم: هوای سالم، آب سالم!', 'slug' => 'season2', 'type' => 'topic'],
                    ['name' => 'فصل سوم: زندگی ما و گردش زمین (1)', 'slug' => 'season3', 'type' => 'topic'],
                    ['name' => 'فصل چهارم: زندگی ما و گردش زمین (2)', 'slug' => 'season4', 'type' => 'topic'],
                    ['name' => 'فصل پنجم: پیام رمز را پیدا کن (1)', 'slug' => 'season5', 'type' => 'topic'],
                    ['name' => 'فصل ششم: پیام رمز را پیدا کن (2)', 'slug' => 'season6', 'type' => 'topic'],
                    ['name' => 'فصل هفتم: اگر تمام شود …', 'slug' => 'season7', 'type' => 'topic'],
                    ['name' => 'فصل هشتم: بسازیم و لذت ببریم', 'slug' => 'season8', 'type' => 'topic'],
                    ['name' => 'فصل نهم: سرگذشت دانه', 'slug' => 'season9', 'type' => 'topic'],
                    ['name' => 'فصل دهم: درون آشیانه ها', 'slug' => 'season10', 'type' => 'topic'],
                    ['name' => 'فصل یازدهم: من رشد می‌کنم', 'slug' => 'season11', 'type' => 'topic'],
                    ['name' => 'فصل دوازدهم: برای جشن آماده شویم', 'slug' => 'season12', 'type' => 'topic'],
                    ['name' => 'فصل سیزدهم: بعد از جشن', 'slug' => 'season13', 'type' => 'topic'],
                    ['name' => 'فصل چهاردهم: از گذشته تا آینده (نان)', 'slug' => 'season14', 'type' => 'topic'],
                ],
            ],
            'third-elementary' => [
                // 'quran' => [
                //     ['name' => 'فصل اول: آموزش نماز', 'slug' => 'season1', 'type' => 'topic'],
                //     ['name' => 'فصل دوم: آموزش روخوانی قرآن کریم', 'slug' => 'season2', 'type' => 'topic'],
                //     ['name' => 'فصل سوم: انس با قرآن کریم', 'slug' => 'season3', 'type' => 'topic'],
                // ],
                'hedyeh-aseman' => [
                    ['name' => 'درس اول: آستین‌های خالی', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: غروب یک روز بهاری', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: هميشه با من', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: در کاخ نمرود', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس پنجم: روز دهم', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: بانوي قهرمان', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: بوی بهشت', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس هشتم: جشن تکلیف', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: گفت گو با خدا', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: ماه مهمانی خدا', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس یازدهم: عید مسلمانان', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: سخن آسمانی', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سیزدهم: انتخاب پروانه', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'درس چهاردهم: ام ابیها', 'slug' => 'lesson14', 'type' => 'topic'],
                    ['name' => 'درس پانزدهم: همسفر ناشناس', 'slug' => 'lesson15', 'type' => 'topic'],
                    ['name' => 'درس شانزدهم: داناترین مردم', 'slug' => 'lesson16', 'type' => 'topic'],
                    ['name' => 'درس هفدهم: خواب شیرین', 'slug' => 'lesson17', 'type' => 'topic'],
                    ['name' => 'درس هجدهم: آینه‌ی سخنگو', 'slug' => 'lesson18', 'type' => 'topic'],
                    ['name' => 'درس نوزدهم: گندم از گندم بروید', 'slug' => 'lesson19', 'type' => 'topic'],
                    ['name' => 'درس بیستم: باغ همیشه بهار', 'slug' => 'lesson20', 'type' => 'topic'],
                ],
                'social-studies' => [
                    ['name' => 'فصل اول: من بزرگ تر می‌شوم', 'slug' => 'season1', 'type' => 'topic'],
                    ['name' => 'درس اول: من به دنیا آمدم', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: من بزرگتر شده‌ام', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: آیا ما مثل هم هستیم', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'فصل دوم: خانواده', 'slug' => 'season2', 'type' => 'topic'],
                    ['name' => 'درس چهارم: اعضای خانواده', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس پنجم: خانواده‌ام را دوست دارم', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: تغییر در خانواده', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: از بزرگترها قدردانی کنیم', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'فصل سوم: همکاری در خانواده', 'slug' => 'season3', 'type' => 'topic'],
                    ['name' => 'درس هشتم: چرا با هم همکاری می‌کنیم', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: مقررات خانه‌ی ما', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'فصل چهارم: نيازهاي خانواده', 'slug' => 'season4', 'type' => 'topic'],
                    ['name' => 'درس دهم: نیازهای خانواده چگونه تأمین می‌شود؟', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس یازدهم: منابع', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: درست مصرف کنیم', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سیزدهم: بازیافت', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'فصل پنجم: خانه ي ما', 'slug' => 'season5', 'type' => 'topic'],
                    ['name' => 'درس چهاردهم: خانه‌ام را دوست دارم', 'slug' => 'lesson14', 'type' => 'topic'],
                    ['name' => 'درس پانزدهم: خانه‌ها با هم تفاوت دارند', 'slug' => 'lesson15', 'type' => 'topic'],
                    ['name' => 'درس شانزدهم: خانه‌ی شما چه شکلی است؟', 'slug' => 'lesson16', 'type' => 'topic'],
                    ['name' => 'درس هفدهم: از خانه محافظت کنیم', 'slug' => 'lesson17', 'type' => 'topic'],
                    ['name' => 'فصل ششم: مدرسه ي ما', 'slug' => 'season6', 'type' => 'topic'],
                    ['name' => 'درس هجدهم: مدرسه‌ی دوست داشتنی ما', 'slug' => 'lesson18', 'type' => 'topic'],
                    ['name' => 'درس نوزدهم: مکان های مدرسه را بشناسیم', 'slug' => 'lesson19', 'type' => 'topic'],
                    ['name' => 'فصل هفتم: از خانه تا مدرسه', 'slug' => 'season7', 'type' => 'topic'],
                    ['name' => 'درس بیستم: خانه‌ی شما کجاست؟', 'slug' => 'lesson20', 'type' => 'topic'],
                    ['name' => 'درس بیست و یکم: جهت‌های اصلی', 'slug' => 'lesson21', 'type' => 'topic'],
                    ['name' => 'درس بیست و دوم: پست', 'slug' => 'lesson22', 'type' => 'topic'],
                    ['name' => 'درس بیست و سوم: ایمنی در کوچه و خیابان', 'slug' => 'lesson23', 'type' => 'topic'],
                ],
                'farsi' => [
                    ['name' => 'درس اوّل: محله‌ی ما', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: زنگِ ورزش', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: آسمان آبی، طبیعت پاک', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: آواز گنجشک', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس پنجم: بلدرچین و برزگر', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: فداکاران', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: کار نیک', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس هشتم: پیراهن بهشتی', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: بوی نرگس', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: یار مهربان', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس یازدهم: نویسنده ی بزرگ', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: ایران عزیز', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سیزدهم: درس آزاد', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'درس چهاردهم: ایران آباد', 'slug' => 'lesson14', 'type' => 'topic'],
                    ['name' => 'درس پانزدهم: دریا', 'slug' => 'lesson15', 'type' => 'topic'],
                    ['name' => 'درس شانزدهم: اگر جنگل نباشد', 'slug' => 'lesson16', 'type' => 'topic'],
                    ['name' => 'درس هفدهم: چشم های آسمان', 'slug' => 'lesson17', 'type' => 'topic'],

                ],
                'math' => [
                    ['name' => 'فصل اول: الگوها', 'slug' => 'season1', 'type' => 'topic'],
                    ['name' => 'فصل دوم: عددهاي چهار رقمی', 'slug' => 'season2', 'type' => 'topic'],
                    ['name' => 'فصل سوم: عددهای کسری', 'slug' => 'season3', 'type' => 'topic'],
                    ['name' => 'فصل چهارم: ضرب و تقسيم', 'slug' => 'season4', 'type' => 'topic'],
                    ['name' => 'فصل پنجم: محيط و مساحت', 'slug' => 'season5', 'type' => 'topic'],
                    ['name' => 'فصل ششم: جمع و تفریق', 'slug' => 'season6', 'type' => 'topic'],
                    ['name' => 'فصل هفتم: آمار و احتمال', 'slug' => 'season7', 'type' => 'topic'],
                    ['name' => 'فصل هشتم: ضرب عددها', 'slug' => 'season8', 'type' => 'topic'],
                ],
                'science' => [
                    ['name' => 'درس اول: زنگ علوم', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: خوراکی ها', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: مواد اطراف ما', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: اندازه گيري مواد', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس پنجم: آب ماده اي با ارزش', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: زندگی ما و آب', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: نور و مشاهده‌ی اجسام', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس هشتم: جست و جو کنیم و بسازیم', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: نیرو همه جا (1)', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: نیرو همه جا (2)', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس يازدهم: بکاريد و ببينيد', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: هر کدام جاي خود (1)', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سيزدهم: هر کدام جاي خود (2)', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'درس چهاردهم: از گذشته تا آينده', 'slug' => 'lesson14', 'type' => 'topic'],
                ],
            ],
            'fourth-elementary' => [
                // 'quran' => [
                //     ['name' => 'درس اول: یادآوری قواعد سالهای قبل', 'slug' => 'lesson1', 'type' => 'topic'],
                //     ['name' => 'درس دوم: سوره تغابن', 'slug' => 'lesson2', 'type' => 'topic'],
                //     ['name' => 'درس سوم: سوره ابراهیم', 'slug' => 'lesson3', 'type' => 'topic'],
                //     ['name' => 'درس چهارم: سوره واقعه', 'slug' => 'lesson4', 'type' => 'topic'],
                //     ['name' => 'درس پنجم: سوره آل عمران آیات 102 تا 105', 'slug' => 'lesson5', 'type' => 'topic'],
                //     ['name' => 'درس ششم: سوره ی اِسراء', 'slug' => 'lesson6', 'type' => 'topic'],
                //     ['name' => 'درس هفتم: آشنایی با خط قرآن کریم', 'slug' => 'lesson7', 'type' => 'topic'],
                //     ['name' => 'درس هشتم: سوره آل عِمران آیات ٣٠ تا ٣٧', 'slug' => 'lesson8', 'type' => 'topic'],
                //     ['name' => 'درس نهم: سوره بقره', 'slug' => 'lesson9', 'type' => 'topic'],
                //     ['name' => 'درس دهم: سوره هود', 'slug' => 'lesson10', 'type' => 'topic'],
                //     ['name' => 'درس یازدهم: سوره مُلک', 'slug' => 'lesson11', 'type' => 'topic'],
                //     ['name' => 'درس دوازدهم: سوره ی آل عِمران آیات 38 تا 45', 'slug' => 'lesson12', 'type' => 'topic'],
                //     ['name' => 'درس سیزدهم: سوره ی نَمل', 'slug' => 'lesson13', 'type' => 'topic'],
                //     ['name' => 'درس چهاردهم: سوره ی یوسف', 'slug' => 'lesson14', 'type' => 'topic'],
                //     ['name' => 'درس پانزدهم: سوره ی عَبَسَ', 'slug' => 'lesson15', 'type' => 'topic'],
                // ],
                'hedyeh-aseman' => [
                    ['name' => 'درس اول: دانه ای که نمی خواست بروید!', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: کودکی بر آب', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: ما به مسجد می رویم', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: یک نماز و ده رکوع!', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس پنجم: سخنی که سه بار تکرار شد!', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: حرمی با دو گنبد', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: نماز در کوهستان', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس هشتم: دیدار دوست', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: کودک شجاع', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: روشن ترین شب', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس یازدهم', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: روزی برای تمام بچه ها', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سیزدهم: خاله نرگس', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'درس چهاردهم: اولین بانوی مسلمان', 'slug' => 'lesson14', 'type' => 'topic'],
                    ['name' => 'درس پانزدهم: یک ماجرای زیبا', 'slug' => 'lesson15', 'type' => 'topic'],
                    ['name' => 'درس شانزدهم: اسب طلایی', 'slug' => 'lesson16', 'type' => 'topic'],
                    ['name' => 'درس هفدهم: آقای بهاری، خانم بهاری', 'slug' => 'lesson17', 'type' => 'topic'],
                    ['name' => 'درس هجدهم: چشمان همیشه باز', 'slug' => 'lesson18', 'type' => 'topic'],
                    ['name' => 'درس نوزدهم: خدا جون از تو ممنونم', 'slug' => 'lesson19', 'type' => 'topic'],
                ],
                'social-studies' => [
                    ['name' => 'فصل اول: محله ی ما', 'slug' => 'season1', 'type' => 'topic'],
                    ['name' => 'درس اول: همسایه‌ی ما', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: اینجا محله‌ی ماست', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: خرید و فروش در محلّه', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: نقشه ی محلّه ی ما', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'فصل دوم: شهر من، روستای من', 'slug' => 'season2', 'type' => 'topic'],
                    ['name' => 'درس پنجم: زندگی در شهر و روستا', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: جهت های جغرافیایی', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: جغرافی دانان چگونه محیط های زندگی را مطالعه می کنند؟', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'فصل سوم: پیدایش شهر و روستا', 'slug' => 'season3', 'type' => 'topic'],
                    ['name' => 'درس هشتم: نخستین روستاها چگونه به وجود آمده اند؟', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: نخستین شهرها چگونه به وجود آمدند؟', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: مورّخان چگونه گذشته را مطالعه می کنند؟', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'فصل چهارم: سفری به شهرهای باستانی', 'slug' => 'season4', 'type' => 'topic'],
                    ['name' => 'درس یازدهم: سفری به شهر باستانی همدان', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: سفری به تخت جمشید (1)', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سیزدهم: سفری به تخت جمشید (2)', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'درس چهاردهم: سفری به شهر باستانی کرمانشاه', 'slug' => 'lesson14', 'type' => 'topic'],
                    ['name' => 'فصل پنجم: کشور زیبای من', 'slug' => 'season5', 'type' => 'topic'],
                    ['name' => 'درس پانزدهم: کوه ها و دشت های زیبا', 'slug' => 'lesson15', 'type' => 'topic'],
                    ['name' => 'درس شانزدهم: آب و هوا', 'slug' => 'lesson16', 'type' => 'topic'],
                    ['name' => 'درس هفدهم: نواحی آب و هوایی ایران', 'slug' => 'lesson17', 'type' => 'topic'],
                    ['name' => 'درس هجدهم: پوشش گیاهی و جانوری', 'slug' => 'lesson18', 'type' => 'topic'],
                    ['name' => 'درس نوزدهم: از محیط زیست مراقبت کنیم', 'slug' => 'lesson19', 'type' => 'topic'],
                    ['name' => 'فصل ششم: ما ایرانی هستیم', 'slug' => 'season6', 'type' => 'topic'],
                    ['name' => 'درس بیستم: نشانه های ملّی ما', 'slug' => 'lesson20', 'type' => 'topic'],
                    ['name' => 'درس بیست و یکم: تقویم', 'slug' => 'lesson21', 'type' => 'topic'],
                    ['name' => 'درس بیست و دوم: روزهای مهم', 'slug' => 'lesson22', 'type' => 'topic'],

                ],
                'farsi' => [
                    ['name' => 'درس اول: آفریدگار زیبایی', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: کوچ پرستوها', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: راز نشانه‌ها', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: ارزش علم', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس پنجم: رهایی از قفس', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: آرش کمان‌گیر', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: مهمان شهر ما', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس هشتم: درس آزاد', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: درس آزاد', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: باغچه‌ی اطفال', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس یازدهم: فرماند‌ی دل‌ها', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: اتّفاق ساده', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سیزدهم: لطفِ حق', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'درس چهاردهم: ادب از که آموختی؟', 'slug' => 'lesson14', 'type' => 'topic'],
                    ['name' => 'درس پانزدهم: شیر و موش', 'slug' => 'lesson15', 'type' => 'topic'],
                    ['name' => 'درس شانزدهم: پرسشگری', 'slug' => 'lesson16', 'type' => 'topic'],
                    ['name' => 'درس هفدهم: مدرسه‌ی هوشمند', 'slug' => 'lesson17', 'type' => 'topic'],

                ],
                'math' => [
                    ['name' => 'فصل اول: اعداد و الگوها', 'slug' => 'season1', 'type' => 'topic'],
                    ['name' => 'فصل دوم: کسر', 'slug' => 'season2', 'type' => 'topic'],
                    ['name' => 'فصل سوم: ضرب و تقسیم', 'slug' => 'season3', 'type' => 'topic'],
                    ['name' => 'فصل چهارم: اندازه گیری', 'slug' => 'season4', 'type' => 'topic'],
                    ['name' => 'فصل پنجم: عدد مخلوط و عدد اعشاری', 'slug' => 'season5', 'type' => 'topic'],
                    ['name' => 'فصل ششم: شکل های هندسی', 'slug' => 'season6', 'type' => 'topic'],
                    ['name' => 'فصل هفتم: آمار و احتمال', 'slug' => 'season7', 'type' => 'topic'],
                ],
                'science' => [
                    ['name' => 'درس اول: زنگ علوم', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: مخلوط ها در زندگی', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: انرژی نیاز هر روز ما', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: انرژی الکتریکی', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس پنجم: گرما و ماده', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: سنگ ها', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: آهن ربا در زندگی', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس هشتم: آسمان در شب', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: بدن ما(1)', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: بدن ما (2)', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس یازدهم: بی مهره ها', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: گوناگونی گیاهان', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سیزدهم: زیستگاه', 'slug' => 'lesson13', 'type' => 'topic'],
                ],
            ],
            'fifth-elementary' => [
                // 'quran' => [
                //     ['name' => 'درس اول: نماز در قرآن', 'slug' => 'lesson1', 'type' => 'topic'],
                //     ['name' => 'درس دوم: یادآوری وقف بر حرکت', 'slug' => 'lesson2', 'type' => 'topic'],
                //     ['name' => 'درس سوم: یادآوری وقف بر ـه و ـه ی', 'slug' => 'lesson3', 'type' => 'topic'],
                //     ['name' => 'درس چهارم: یادآوری وقف ـۀ ۀ', 'slug' => 'lesson4', 'type' => 'topic'],
                //     ['name' => 'درس پنجم: التقاء ساکنین', 'slug' => 'lesson5', 'type' => 'topic'],
                //     ['name' => 'درس ششم: یادآوری حروف مقطّعه', 'slug' => 'lesson6', 'type' => 'topic'],
                //     ['name' => 'درس هفتم: یادآوری مدّ', 'slug' => 'lesson7', 'type' => 'topic'],
                //     ['name' => 'درس هشتم: وقف بر ـــًــ ا و ـــًــ ی', 'slug' => 'lesson8', 'type' => 'topic'],
                //     ['name' => 'درس نهم: یادآوری التقاء ساکنین', 'slug' => 'lesson9', 'type' => 'topic'],
                //     ['name' => 'درس دهم: یادآوری مد', 'slug' => 'lesson10', 'type' => 'topic'],
                //     ['name' => 'درس یازدهم: یادآوری وقف', 'slug' => 'lesson11', 'type' => 'topic'],
                //     ['name' => 'درس دوازدهم: سوره ی انبیاء', 'slug' => 'lesson12', 'type' => 'topic'],
                // ],
                'hedyeh-aseman' => [
                    ['name' => 'درس اول: دسته گلی از آسمان', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: تنها او', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: بانویی که یک سوره ی قرآن به نام اوست', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: از نوزاد بپرسید!', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس پنجم: گل صد برگ', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: مال مردم', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: رنگین کمان جمعه', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس هشتم: دو نامه', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: یک جهان جشن!', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: در ساحل دجله', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس یازدهم: سرو سربلند سامرا', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: خورشید پشت ابر', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سیزدهم: کوچک های بزرگ!', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'درس چهاردهم: بزرگ مرد تاریخ', 'slug' => 'lesson14', 'type' => 'topic'],
                    ['name' => 'درس پانزدهم: بهمن همیشه بهار', 'slug' => 'lesson15', 'type' => 'topic'],
                    ['name' => 'درس شانزدهم: روزنامه های دیواری', 'slug' => 'lesson16', 'type' => 'topic'],
                    ['name' => 'درس هفدهم: این ها و آنها', 'slug' => 'lesson17', 'type' => 'topic'],
                ],
                'social-studies' => [
                    ['name' => 'فصل اول: زندگی با دیگران', 'slug' => 'season1', 'type' => 'topic'],
                    ['name' => 'درس اول: من با دیگران ارتباط برقرار می‌کنم', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: احساسات ما', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: همدلی با دیگران', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: من عضو گروه هستم', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'فصل دوم: سرزمین ما', 'slug' => 'season2', 'type' => 'topic'],
                    ['name' => 'درس پنجم: جمعیت ایران', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: منابع اب ایران', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: نواحی صنعتی مهم ایران', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس هشتم: راه ها و حمل و نقل (۱)', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: راه ها و حمل و نقل (۲)', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: کشور ما چگونه اداره می شود؟', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'فصل سوم: زندگی در نواحی دیگر جهان', 'slug' => 'season3', 'type' => 'topic'],
                    ['name' => 'درس یازدهم: کشورهای همسایه (۱) و کشورهای همسایه (2)', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: حرکت های زمین', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سیزدهم: زندگی در نواحی مختلف جهان', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'فصل چهارم: زیارت مکان های مقدس', 'slug' => 'season4', 'type' => 'topic'],
                    ['name' => 'درس چهاردهم: بازگشت از سفر حج', 'slug' => 'lesson14', 'type' => 'topic'],
                    ['name' => 'درس پانزدهم: مدینه شهر پیامبر (ص)', 'slug' => 'lesson15', 'type' => 'topic'],
                    ['name' => 'درس شانزدهم: سفر به کربلا (۱)', 'slug' => 'lesson16', 'type' => 'topic'],
                    ['name' => 'درس هفدهم: سفر به کربلا (۲)', 'slug' => 'lesson17', 'type' => 'topic'],
                    ['name' => 'فصل پنجم: ایران بعد از اسلام', 'slug' => 'season5', 'type' => 'topic'],
                    ['name' => 'درس هجدهم: ایرانیان مسلمان حکومت تشکیل می دهند', 'slug' => 'lesson18', 'type' => 'topic'],
                    ['name' => 'درس نوزدهم: وزیران کاردان، شهرهای آباد', 'slug' => 'lesson19', 'type' => 'topic'],
                    ['name' => 'درس بیست: کشورگشایان بی رحم', 'slug' => 'lesson20', 'type' => 'topic'],
                    ['name' => 'درس بیست و یکم: بازسازی ویرانه ها', 'slug' => 'lesson21', 'type' => 'topic'],

                ],
                'farsi' => [
                    ['name' => 'درس اول: تماشاخانه', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: فضلِ خدا', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: رازی و ساخت بیمارستان', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: بازرگان و پسران', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس پنجم: چنار و کدوبُن', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: سرود ملی', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: درس آزاد', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس هشتم: دفاع از میهن', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: نام آوران دیروز، امروز ، فردا', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: نامِ نیکو', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس یازدهم: نقشِ خردمندان', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: درس آزاد', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سیزدهم: روزی که باران می‌بارید', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'درس چهاردهم: شجاعت', 'slug' => 'lesson14', 'type' => 'topic'],
                    ['name' => 'درس پانزدهم: کاجستان', 'slug' => 'lesson15', 'type' => 'topic'],
                    ['name' => 'درس شانزدهم: وقتی بوعلی، کودک بود', 'slug' => 'lesson16', 'type' => 'topic'],
                    ['name' => 'درس هفدهم: کار و تلاش', 'slug' => 'lesson17', 'type' => 'topic'],

                ],
                'math' => [
                    ['name' => 'فصل اول: عدد نویسی و الگوها', 'slug' => 'season1', 'type' => 'topic'],
                    ['name' => 'فصل دوم: کسر', 'slug' => 'season2', 'type' => 'topic'],
                    ['name' => 'فصل سوم: نسبت، تناسب و درصد', 'slug' => 'season3', 'type' => 'topic'],
                    ['name' => 'فصل چهارم: تقارن و چند ضلعی ها', 'slug' => 'season4', 'type' => 'topic'],
                    ['name' => 'فصل پنجم: عددهای اعشاری', 'slug' => 'season5', 'type' => 'topic'],
                    ['name' => 'فصل ششم: اندازه گیری', 'slug' => 'season6', 'type' => 'topic'],
                    ['name' => 'فصل هفتم: آمار و احتمال', 'slug' => 'season7', 'type' => 'topic'],
                ],
                'science' => [
                    ['name' => 'درس اول: زنگ علوم', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: ماده تغییر می کند', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: رنگین کمان', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: برگی از تاریخ زمین', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس پنجم: حرکت بدن', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: چه خبر؟(1)', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: چه خبر؟(2)', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس هشتم: کارها آسان می شود(1)', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: کارها آسان می شود(2)', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: خاک با ارزش', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس یازدهم: بکارید، بخورید', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: از ریشه تا برگ', 'slug' => 'lesson12', 'type' => 'topic'],
                ],
            ],
            'sixth-elementary' => [
                // 'quran' => [
                //     ['name' => 'درس اول: سوره ی انفال (وقت نماز)', 'slug' => 'lesson1', 'type' => 'topic'],
                //     ['name' => 'درس دوم: سوره ی فتح (حتی یک وجب خاک)', 'slug' => 'lesson2', 'type' => 'topic'],
                //     ['name' => 'درس سوم: سوره ی فتح و حجرات (مومنان برادرند)', 'slug' => 'lesson3', 'type' => 'topic'],
                //     ['name' => 'درس چهارم: سوره ی حجرات (ملاک برتری)', 'slug' => 'lesson4', 'type' => 'topic'],
                //     ['name' => 'درس پنجم: سوره ی ق و ذاریات (گسترش آسمان)', 'slug' => 'lesson5', 'type' => 'topic'],
                //     ['name' => 'درس ششم: سوره ی ذاریات و طور (همیشه در تپش)', 'slug' => 'lesson6', 'type' => 'topic'],
                //     ['name' => 'درس هفتم: سوره ی قمر (نظم در آفرینش)', 'slug' => 'lesson7', 'type' => 'topic'],
                //     ['name' => 'درس هشتم: سوره ی الرحمن (مردان پارسی)', 'slug' => 'lesson8', 'type' => 'topic'],
                //     ['name' => 'درس نهم: سوره ی الرحمن و واقعه (آب و آبادانی)', 'slug' => 'lesson9', 'type' => 'topic'],
                //     ['name' => 'درس دهم: سوره ی حدید (تولدی دوباره)', 'slug' => 'lesson10', 'type' => 'topic'],
                //     ['name' => 'درس یازدهم: سوره ی حدید (مادر فلزات)', 'slug' => 'lesson11', 'type' => 'topic'],
                //     ['name' => 'درس دوازدهم: سوره مجادله (حزب الله پیروز است)', 'slug' => 'lesson12', 'type' => 'topic'],
                //     ['name' => 'درس سیزدهم: حشر (تصویرگر)', 'slug' => 'lesson13', 'type' => 'topic'],
                //     ['name' => 'درس چهاردهم: سوره ی ممتحنه و صف (همه تسبیح گوی او …)', 'slug' => 'lesson14', 'type' => 'topic'],
                // ],
                'hedyeh-aseman' => [
                    ['name' => 'درس اول: تنها او', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: تنها تو را می پرستیم', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: جهان دیگر', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: یاد آن روز بزرگ', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس پنجم: شتربان با ایمان', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: سیمای خوبان', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: دست در دست دوست', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس هشتم: دوران غیبت', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: جهان دیگر', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: آداب زندگی', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس یازدهم: راه تندرستی', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: احکام سفر', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سیزدهم: عید مسلمانان', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'درس چهاردهم: راز موفقیت', 'slug' => 'lesson14', 'type' => 'topic'],
                    ['name' => 'درس پانزدهم: رهبر کوچک', 'slug' => 'lesson15', 'type' => 'topic'],
                    ['name' => 'درس شانزدهم: زیارت', 'slug' => 'lesson16', 'type' => 'topic'],
                    ['name' => 'درس هفدهم: دانش آموز نمونه', 'slug' => 'lesson17', 'type' => 'topic'],
                ],
                'social-studies' => [
                    ['name' => 'فصل اول: دوستان ما', 'slug' => 'season1', 'type' => 'topic'],
                    ['name' => 'فصل دوم: تصمیم گیری', 'slug' => 'season2', 'type' => 'topic'],
                    ['name' => 'فصل سوم: کشاورزی در ایران', 'slug' => 'season3', 'type' => 'topic'],
                    ['name' => 'فصل چهارم: ایران و منابع انرژی', 'slug' => 'season4', 'type' => 'topic'],
                    ['name' => 'فصل پنجم: پیشرفت علوم و فنون در دوره‌ی اسلامی', 'slug' => 'season5', 'type' => 'topic'],
                    ['name' => 'فصل ششم: سفری به اصفهان', 'slug' => 'season6', 'type' => 'topic'],
                    ['name' => 'فصل هفتم: اوقات فراغت', 'slug' => 'season7', 'type' => 'topic'],
                    ['name' => 'فصل هشتم: پوشاک ما', 'slug' => 'season8', 'type' => 'topic'],
                    ['name' => 'فصل نهم: دریاهای ایران', 'slug' => 'season9', 'type' => 'topic'],
                    ['name' => 'فصل دهم: ایران و همسایگان', 'slug' => 'season10', 'type' => 'topic'],
                    ['name' => 'فصل یازدهم: ایستادگی در برابر بیگانگان', 'slug' => 'season11', 'type' => 'topic'],
                    ['name' => 'فصل دوازدهم: آزادی خرمشهر', 'slug' => 'season12', 'type' => 'topic'],

                ],
                'farsi' => [
                    ['name' => 'فصل اوّل: آفرينش', 'slug' => 'season1', 'type' => 'topic'],
                    ['name' => 'فصل دوم: دانایی و هوشیاری', 'slug' => 'season2', 'type' => 'topic'],
                    ['name' => 'فصل سوم: ايران من', 'slug' => 'season3', 'type' => 'topic'],
                    ['name' => 'فصل چهارم: نام آوران', 'slug' => 'season4', 'type' => 'topic'],
                    ['name' => 'فصل پنجم: راهِ زندگی', 'slug' => 'season5', 'type' => 'topic'],
                    ['name' => 'فصل ششم: علم و عمل', 'slug' => 'season6', 'type' => 'topic'],
                ],
                'math' => [
                    ['name' => 'فصل اول: عدد و الگوهای عددی', 'slug' => 'season1', 'type' => 'topic'],
                    ['name' => 'فصل دوم: کسر', 'slug' => 'season2', 'type' => 'topic'],
                    ['name' => 'فصل سوم: اعداد اعشاری', 'slug' => 'season3', 'type' => 'topic'],
                    ['name' => 'فصل چهارم: تقارن و مختصات', 'slug' => 'season4', 'type' => 'topic'],
                    ['name' => 'فصل پنجم: اندازه گیری', 'slug' => 'season5', 'type' => 'topic'],
                    ['name' => 'فصل شش: تناسب و درصد', 'slug' => 'season6', 'type' => 'topic'],
                    ['name' => 'فصل هفت: تقریب', 'slug' => 'season7', 'type' => 'topic'],
                ],
                'science' => [
                    ['name' => 'درس اول: زنگ علوم', 'slug' => 'lesson1', 'type' => 'topic'],
                    ['name' => 'درس دوم: سرگذشت دفتر من', 'slug' => 'lesson2', 'type' => 'topic'],
                    ['name' => 'درس سوم: کارخانه ی کاغذ سازی', 'slug' => 'lesson3', 'type' => 'topic'],
                    ['name' => 'درس چهارم: سفر به اعماق زمین', 'slug' => 'lesson4', 'type' => 'topic'],
                    ['name' => 'درس پنجم: زمین پویا', 'slug' => 'lesson5', 'type' => 'topic'],
                    ['name' => 'درس ششم: ورزش و نیرو (1)', 'slug' => 'lesson6', 'type' => 'topic'],
                    ['name' => 'درس هفتم: ورزش و نیرو (2)', 'slug' => 'lesson7', 'type' => 'topic'],
                    ['name' => 'درس هشتم: طراحی کنیم و بسازیم', 'slug' => 'lesson8', 'type' => 'topic'],
                    ['name' => 'درس نهم: سفر انرژی', 'slug' => 'lesson9', 'type' => 'topic'],
                    ['name' => 'درس دهم: خیلی کوچک، خیلی بزرگ', 'slug' => 'lesson10', 'type' => 'topic'],
                    ['name' => 'درس یازدهم: شگفتی های برگ', 'slug' => 'lesson11', 'type' => 'topic'],
                    ['name' => 'درس دوازدهم: جنگل برای کیست؟', 'slug' => 'lesson12', 'type' => 'topic'],
                    ['name' => 'درس سیزدهم: سالم بمانیم', 'slug' => 'lesson13', 'type' => 'topic'],
                    ['name' => 'درس چهاردهم: از گذشته تا آینده', 'slug' => 'lesson14', 'type' => 'topic'],
                ],
                'thinking-research' => [],
                'work-technology' => [],
            ],
        ];

        foreach ($grades as $gradeData) {
            $grade = Category::create($gradeData);

            $gradeSubjects = $subjects[$gradeData['slug']] ?? [];

            foreach ($gradeSubjects as $subjectData) {
                $subject = Category::create([
                    'parent_id' => $grade->id,
                    'name' => $subjectData['name'],
                    'slug' => $subjectData['slug'],
                    'type' => $subjectData['type'],
                    'icon' => $subjectData['icon'],
                ]);

                $subjectTopics = $topics[$gradeData['slug']][$subjectData['slug']] ?? [];

                foreach ($subjectTopics as $topicData) {
                    Category::create([
                        'parent_id' => $subject->id,
                        'name' => $topicData['name'],
                        'slug' => $topicData['slug'],
                        'type' => $topicData['type'],
                    ]);
                }
            }
        }
    }
}
